/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 isometric_blender_inception.glb 
Author: ariskay (https://sketchfab.com/ariskay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/isometric-blender-inception-671428654bd14bca95b9fb8d5b1fc02f
Title: isometric blender inception
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/isometric_blender_inception.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, -1]} scale={[8, 8, 1]}>
          <mesh geometry={nodes.floor_0.geometry} material={materials.walls_outisde} />
          <mesh geometry={nodes.floor_1.geometry} material={materials.floor} />
        </group>
        <group position={[0, 7.5, 0]} scale={[8, 0.5, 1]}>
          <mesh geometry={nodes.walls_0.geometry} material={materials.walls} />
          <mesh geometry={nodes.walls_1.geometry} material={materials.walls_internal} />
          <mesh geometry={nodes.walls_2.geometry} material={materials.walls_bottom} />
          <mesh geometry={nodes.walls_3.geometry} material={materials.walls_outisde} />
        </group>
        <group position={[5.855, 1.351, 3.415]}>
          <mesh geometry={nodes.monitor_0.geometry} material={materials.screen} />
          <mesh geometry={nodes.monitor_1.geometry} material={materials.screen_border} />
          <mesh geometry={nodes.monitor_2.geometry} material={materials.inception} />
        </group>
        <group position={[-6.613, 5.188, 2.316]}>
          <mesh geometry={nodes.plant_0.geometry} material={materials.material_16} />
          <mesh geometry={nodes.plant_1.geometry} material={materials.soil} />
          <mesh geometry={nodes.plant_2.geometry} material={materials.branch} />
          <mesh geometry={nodes.plant_3.geometry} material={materials.leafs} />
        </group>
        <group position={[6.559, 4.508, 5.561]}>
          <mesh geometry={nodes.book01_0.geometry} material={materials.book} />
          <mesh geometry={nodes.book01_1.geometry} material={materials.bookpaper} />
        </group>
        <group position={[6.559, 4.097, 5.561]}>
          <mesh geometry={nodes.book02_0.geometry} material={materials.book} />
          <mesh geometry={nodes.book02_1.geometry} material={materials.bookpaper} />
        </group>
        <group position={[6.559, 3.555, 5.567]} rotation={[-0.352, 0, 0]}>
          <mesh geometry={nodes.book03_0.geometry} material={materials.book} />
          <mesh geometry={nodes.book03_1.geometry} material={materials.bookpaper} />
        </group>
        <group position={[6.559, 3.07, 5.561]}>
          <mesh geometry={nodes.book04_0.geometry} material={materials.book} />
          <mesh geometry={nodes.book04_1.geometry} material={materials.bookpaper} />
        </group>
        <group position={[6.559, 2.824, 5.561]}>
          <mesh geometry={nodes.book05_0.geometry} material={materials.book} />
          <mesh geometry={nodes.book05_1.geometry} material={materials.bookpaper} />
        </group>
        <group position={[6.2, -0.014, 5.195]}>
          <mesh geometry={nodes.camera_0.geometry} material={materials.lense} />
          <mesh geometry={nodes.camera_1.geometry} material={materials.flash} />
          <mesh geometry={nodes.camera_2.geometry} material={materials.camera} />
        </group>
        <group position={[6.914, -4.355, 4.41]}>
          <mesh geometry={nodes.paint01_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.paint01_1.geometry} material={materials.paint02} />
        </group>
        <group position={[4.559, 6.884, 4.41]}>
          <mesh geometry={nodes.paint02_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.paint02_1.geometry} material={materials.paint01} />
        </group>
        <group position={[6.914, -6.336, 4.023]}>
          <mesh geometry={nodes.paint03_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.paint03_1.geometry} material={materials.paint03} />
        </group>
        <group position={[6.914, -4.21, 2.503]}>
          <mesh geometry={nodes.paint04_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.paint04_1.geometry} material={materials.paint04} />
        </group>
        <group position={[5.139, -2.964, 0.605]}>
          <mesh geometry={nodes.trash_0.geometry} material={materials.trash} />
          <mesh geometry={nodes.trash_1.geometry} material={materials.material_5} />
        </group>
        <group position={[-2.731, -5.669, 1.573]}>
          <mesh geometry={nodes.sofa_0.geometry} material={materials.shelf} />
          <mesh geometry={nodes.sofa_1.geometry} material={materials.table} />
        </group>
        <mesh geometry={nodes.shelf_0.geometry} material={materials.shelf} position={[6.4, 1.5, 4.805]} />
        <mesh geometry={nodes.table_0.geometry} material={materials.table} position={[5.2, 1.5, 1.2]} />
        <mesh geometry={nodes.chair_0.geometry} material={materials.chair} position={[3.407, 1.447, 1.652]} />
        <mesh geometry={nodes.keyboard_0.geometry} material={materials.screen} position={[4.8, 1.662, 2.437]} />
        <mesh geometry={nodes.mouse_0.geometry} material={materials.screen} position={[4.67, 0.144, 2.437]} />
        <mesh geometry={nodes.mat_0.geometry} material={materials.material} position={[-2.166, 0.357, 0.016]} />
        <mesh geometry={nodes.paperball01_0.geometry} material={materials.paperballs} position={[5.149, -3.128, 0.686]} />
        <mesh geometry={nodes.paperball02_0.geometry} material={materials.paperballs} position={[4.99, -2.882, 0.69]} />
        <mesh geometry={nodes.paperball03_0.geometry} material={materials.paperballs} position={[5.244, -2.879, 0.903]} />
        <mesh geometry={nodes.paperball04_0.geometry} material={materials.paperballs} position={[5.308, -3.818, 0.175]} />
        <mesh geometry={nodes.paperball05_0.geometry} material={materials.paperballs} position={[4.845, -3.962, 0.175]} />
      </group>
    </group>
  )
}

useGLTF.preload('/isometric_blender_inception.glb')
