/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lowpoly_room.glb 
Author: Gavin B. (https://sketchfab.com/Gevin_B.)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-room-3a0891d4e26a4cd2838e40839359b985
Title: lowpoly_Room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/models/lowpoly_room.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[3.771, 0.652, 3.115]} scale={[0.038, 0.313, 0.437]}>
        <mesh geometry={nodes.Object_20.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['Material.014']} />
      </group>
      <group position={[2.164, 1.437, 0.002]} rotation={[0, Math.PI / 2, 0]} scale={[0.043, 0.452, 0.496]}>
        <mesh geometry={nodes.Object_27.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['Material.016']} />
      </group>
      <group position={[1.065, 1.031, 0.266]} rotation={[0, Math.PI / 2, 0]} scale={[0.014, 0.251, 0.396]}>
        <mesh geometry={nodes.Object_34.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_35.geometry} material={materials['Material.006']} />
      </group>
      <group position={[3.996, 1.59, 3.133]} scale={[0.034, 0.288, 0.308]}>
        <mesh geometry={nodes.Object_73.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Object_74.geometry} material={materials['Material.018']} />
      </group>
      <group position={[4.1, 1.306, 2.14]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_7.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Plastic} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Marble} />
      </group>
      <group position={[4.1, 1.306, 1.135]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_12.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Plastic} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Marble} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.009']} position={[3.73, 0.934, 0.618]} scale={[0.088, 0.858, 0.56]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['Material.033']} position={[3.935, 0.123, 3.598]} scale={[0.04, 0.04, 0.059]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials['Material.012']} position={[2.021, 0.115, 3.297]} scale={0.043} />
      <mesh geometry={nodes.Object_25.geometry} material={materials['Material.011']} position={[1.018, 0.32, 2.897]} scale={[0.286, 0.286, 0.339]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['Material.003']} position={[1.018, 0.657, 0.392]} scale={[0.701, 0.036, 0.357]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['Material.004']} position={[1.07, 0.097, 1.054]} rotation={[0, -0.102, 0]} scale={[0.021, 0.022, 0.022]} />
      <mesh geometry={nodes.Object_37.geometry} material={materials['Material.007']} position={[1.072, 0.701, 0.29]} scale={[0.1, 0.009, 0.018]} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.material_0} position={[0.82, 0.696, 0.513]} rotation={[0, 0.25, 0]} scale={[0.212, 0.007, 0.066]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.material_0} position={[1.289, 0.697, 0.539]} rotation={[0, 0.196, 0]} scale={[0.025, 0.005, 0.041]} />
      <mesh geometry={nodes.Object_43.geometry} material={materials['Material.010']} position={[1.29, 0.693, 0.539]} scale={[0.129, 0.002, 0.117]} />
      <mesh geometry={nodes.Object_45.geometry} material={materials['Material.025']} position={[3.653, 0.855, 0.509]} scale={[0.046, 0.187, 0.163]} />
      <mesh geometry={nodes.Object_47.geometry} material={materials['Material.029']} position={[3.552, 0.855, 0.509]} scale={[0.046, 0.187, 0.163]} />
      <mesh geometry={nodes.Object_49.geometry} material={materials['Material.024']} position={[3.401, 0.83, 0.534]} rotation={[0, 0, -0.435]} scale={[0.038, 0.154, 0.134]} />
      <mesh geometry={nodes.Object_51.geometry} material={materials['Material.022']} position={[3.27, 0.815, 0.498]} rotation={[0, 0, -0.665]} scale={[0.038, 0.154, 0.134]} />
      <mesh geometry={nodes.Object_53.geometry} material={materials['Material.021']} position={[3.146, 0.815, 0.52]} rotation={[0, 0, -0.764]} scale={[0.038, 0.154, 0.134]} />
      <mesh geometry={nodes.Object_55.geometry} material={materials['Material.031']} position={[3.124, 1.417, 0.509]} scale={[0.046, 0.187, 0.163]} />
      <mesh geometry={nodes.Object_57.geometry} material={materials['Material.026']} position={[3.023, 1.417, 0.509]} scale={[0.046, 0.187, 0.163]} />
      <mesh geometry={nodes.Object_59.geometry} material={materials['Material.030']} position={[3.228, 1.417, 0.496]} scale={[0.046, 0.187, 0.163]} />
      <mesh geometry={nodes.Object_61.geometry} material={materials['Material.027']} position={[3.676, 1.356, 0.541]} scale={[0.033, 0.136, 0.119]} />
      <mesh geometry={nodes.Object_63.geometry} material={materials['Material.032']} position={[3.603, 1.356, 0.538]} scale={[0.033, 0.136, 0.119]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials['Material.028']} position={[3.529, 1.356, 0.529]} scale={[0.033, 0.136, 0.119]} />
      <mesh geometry={nodes.Object_67.geometry} material={materials['Material.023']} position={[3.451, 1.356, 0.538]} scale={[0.033, 0.136, 0.119]} />
      <mesh geometry={nodes.Object_69.geometry} material={materials['Material.020']} position={[3.175, 0.28, 0.509]} rotation={[0, 0, -1.571]} scale={[0.044, 0.181, 0.158]} />
      <mesh geometry={nodes.Object_71.geometry} material={materials['Material.019']} position={[3.191, 0.372, 0.509]} rotation={[0, 0, -1.571]} scale={[0.044, 0.181, 0.158]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials['Material.008']} position={[1.908, 0.089, 0.697]} scale={0.081} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.Material} position={[2.027, -0.022, 1.974]} scale={[2.122, 0.067, 2.122]} />
    </group>
  )
}

useGLTF.preload('/models/lowpoly_room.glb')
